<?php
/**
 * @author      John Herholz <info@longneckdesigns.de>
 * @copyright   Longneck Designs, 2018
 * @license     See license.txt
 **/

if($block->getIsSampleRequest() == 1 || $this->getIsStandalone() == 1) :
?>
    <div id="request-form" <?php if(!$this->getIsStandalone() == 1) :?> style="display:none" <?php endif; ?>>

        <form class="form form-sample-request" id="sample-request-form" data-mage-init='{"validation":{}}' action="<?= /* @escapeNotVerified */ $block->getFormAction() ?>"
          method="post" name="guest_post">
        <fieldset class="fieldset">
            <legend class="admin__legend"><span><?= /* @escapeNotVerified */ $block->getTextHint(); ?></span></legend>
            <br>
            <div class="field region required">
                <label for="product_id" class="label"><span><?= $block->escapeHtml(__('Product')) ?></span></label>
                <div class="control">
                    <select id="product_id" name="product_id" title="<?= $block->escapeHtmlAttr(__('Product')) ?>" class="validate-select" data-validate="{required:true}">
                        <option value=""><?= $block->escapeHtml(__('Select product')) ?></option>
                        <?php
                        $productCollection = $block->getProductCollection();
                        foreach ($productCollection as $product) { ?>
                            <option value="<?php echo $product->getSku();?>"
                            <?php echo ($product->getSku() == $block->getProductSku() ?  'selected="selected"' : '');?>>
                                <?php echo $product->getName(). " | " . $product->getSku();?>
                            </option>
                        <?php } ?>
                    </select>
                </div>
            </div>

            <div class="field required">
                <label class="label" for="sample-email"><span><?= /* @escapeNotVerified */ __('Email') ?></span></label>
                <div class="control">
                    <input type="email" class="input-text" id="sample-email" name="sample-email"
                           data-validate="{required:true, 'validate-email':true}"/>
                </div>
            </div>

            <div class="field">
                <label class="label" for="sample-phone"><span><?= /* @escapeNotVerified */ __('Phone') ?></span></label>
                <div class="control">
                    <input type="text" class="input-text" id="sample-phone" name="sample-phone"/>
                </div>
            </div>

            <div class="field required">
                <label for="sample-firstname" class="label"><?php echo __('First Name');?></label>
                <div class="control">
                    <input type="text" name="sample-firstname" id="sample-firstname" value="" title="<?php echo __('First Name');?>" class="required-entry input-text" data-validate="{required:true}"/>
                </div>
            </div>

            <div class="field required">
                <label for="sample-lastname" class="label"><?php echo __('Last Name');?></label>
                <div class="control">
                    <input type="text" name="sample-lastname" id="sample-lastname" value="" title="<?php echo __('Last Name');?>" class="required-entry input-text"  data-validate="{required:true}"/>
                </div>
            </div>

            <div class="field street required">
                <label for="sample-street_1" class="label"><span><?= $block->escapeHtml(__('Street Address')) ?></span></label>
                <div class="control">
                    <input type="text" name="sample-street_1" value="" title="<?= $block->escapeHtmlAttr(__('Street Address')) ?>" id="sample-street_1" class="input-text"  data-validate="{required:true}">
                    <div class="nested">
                        <?php for ($_i = 2, $_n = $this->helper('Magento\Customer\Helper\Address')->getStreetLines(); $_i <= $_n; $_i++): ?>
                            <div class="field additional">
                                <label class="label" for="street_<?= /* @noEscape */ $_i ?>">
                                    <span><?= $block->escapeHtml(__('Address')) ?></span>
                                </label>
                                <div class="control">
                                    <input type="text" name="sample-street_<?= /* @noEscape */ $_i ?>" value="" title="<?= $block->escapeHtmlAttr(__('Street Address %1', $_i)) ?>" id="sample-street_<?= /* @noEscape */ $_i ?>" class="input-text">
                                </div>
                            </div>
                        <?php endfor; ?>
                    </div>
                </div>
            </div>

            <div class="field required">
                <label for="sample-zip" class="label"><span><?= $block->escapeHtml(__('Zip/Postal Code')) ?></span></label>
                <div class="control">
                    <input type="text" name="sample-zip" value="" title="" id="sample-zip" class="input-text validate-zip-international <?= $this->helper('Magento\Customer\Helper\Address')->getAttributeValidationClass('postcode') ?>" data-validate="{required:true}">
                </div>
            </div>

            <div class="field required">
                <label for="sample-city" class="label"><span><?= $block->escapeHtml(__('City')) ?></span></label>
                <div class="control">
                    <input type="text" name="sample-city" value="" title="" id="sample-city" class="input-text" data-validate="{required:true}">
                </div>
            </div>

            <div class="field country required">
                <label for="country" class="label"><span><?= $block->escapeHtml(__('Country')) ?></span></label>
                <div class="control">
                    <?= $block->getCountryHtmlSelect() ?>
                </div>
            </div>

            <div class="field comment">
                <label class="label" for="sample-comment"><span><?php /* @escapeNotVerified */ echo __('Message') ?></span></label>
                <div class="control">
                    <textarea name="comment" id="sample-comment" title="<?php /* @escapeNotVerified */ echo __('Message') ?>" class="input-text" cols="5" rows="3"><?php echo $block->escapeHtml($this->helper('Magento\Contact\Helper\Data')->getPostValue('comment')) ?></textarea>
                </div>
            </div>

            <div class="field required">
                <div class="control">
                    <input type="checkbox" class="input-checkbox" id="sample-terms" name="sample-checkbox" data-validate="{required:true}"/>
                    <label class="label" for="sample-terms"><span><?php /* @escapeNotVerified */ echo __('I agree to the <a href="%1">terms of service</a> and <a href="%2">privacy policy</a>',$block->getUrl('terms-of-service'),$block->getUrl('privacy-policy')) ?></span></label>
                </div>
            </div>
        </fieldset>
        <div>
            <div class="primary">
                <input type="hidden" name="hideit" id="hideit" value="" />
                <button type="submit" title="<?= /* @escapeNotVerified */ __('Submit') ?>" class="action submit primary">
                    <span><?= /* @escapeNotVerified */ __('Submit') ?></span>
                </button>
            </div>
        </div>
    </form>
</div>
<?php endif; ?>